### ISSUE TITLE
Threads piling up when on a loop. Some say to trim these down after my code has executed a single loop?

### ISSUE THREAD

**Issue by Swimmerhair** [dgilman/gspread_asyncio#18]
Hi there, 

I basically am reading a random row of data every 5 seconds, but the program (expectedly) is making a new thread every loop. Is there any adverse effects to leaving these threads open for long periods of time (somewhere in the range of weeks at a time)? Can I close the thread at the end of the code loop in someway so as to save memory (if it affects memory)?

Code: 
`async def run(agcm):

    while True:

        gclient = await agcm.authorize()

        sheet = await gclient.open_by_key('1Hkwo9gSpk3NjgPLPkG8kh0zBNw2nxsYWRw0cVdn0JA0')

        ws = await sheet.get_worksheet(0)

        rcount = ws.row_count

        msg = await ws.cell(random.randint(1,rcount),1)

        msg = msg.value

        print(msg)

        await asyncio.sleep(5)`

**Comment by dgilman** [comment]
Are there any adverse effects from having so many threads? Not that I know of. My code that uses `gspread_asyncio` is also a long-running piece of software and hasn't run into any issues with it. Each thread needs its own stack space but stacks don't take up a whole lot of memory, a couple of megabytes each. Can you close threads to save memory? If you tear down the whole asyncio event loop it'll shut down the threads and reclaim the memory but that's a lot of work to save on a little bit of memory.

If the maximum thread count is a concern to you it is better to set a new default executor for your asyncio event loop that has a lower maximum thread count. I can also patch `gspread_asyncio` to let you pass in the executor to use and you could pass in one with a low maximum thread count. It's kind of funny that the second issue opened against this library has to do with changing the threadpool executor, because I remember looking at that code and telling myself "nobody's ever going to need to mess with this!"

To explain the behavior that you're seeing:

`gspread_asyncio` uses the event loop's default executor, and the default default executor is an instance of this: https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor It has a default maximum thread pool size of cpu count * 5.

If you take a look at the asyncio code, you can see that in the `submit()` method (the method that is called when a new work item is sent to the thread pool) calls `_adjust_thread_count()`:
https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Lib/concurrent/futures/thread.py#L160

And if you look at the implementation of `_adjust_thread_count()` you can see that it creates a single new thread each time it is called until you reach the maximum number of threads: https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Lib/concurrent/futures/thread.py#L164 There's a TODO comment in there explaining this behavior and asking to change it later.

**Comment by Swimmerhair** [comment]
Thanks for the response! To be honest, I'm not THAT worried about the thread count or memory usage, but I will have my program running on a raspberry pi, so I just didn't want the threads to pile up and eventually crash the program because of running out of memory.

When the maximum thread count is reached and I keep calling on the loop, are the old threads just written over? I know this is more of a fundamental question, so forgive me if I sound like I don't know what I'm doing (I know just enough to be dangerous, but I'm not a programmer by trade or anything!)

**Comment by dgilman** [comment]
It won't make any more threads when it reaches the limit. See line 172, https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Lib/concurrent/futures/thread.py#L172 The code to spawn a new thread will only run if you are under the maximum number of threads.

**Comment by Swimmerhair** [comment]
That's all I needed to know. I wasn't sure if it just kept on creating threads and using memory indefinitely. I love the library so far though!
