### ISSUE TITLE
[question] is it necessary for all calls to be wrapped in lock? does a copy call need lock?

### ISSUE THREAD

**Issue by pawciobiel** [dgilman/gspread_asyncio#51]

**Comment by dgilman** [comment]
The purpose of the lock is to intentionally delay the calls to avoid bumping into Google's aggressive rate limiting. There are a handful of other ways to do this, this was the straightforward one I implemented first, but ultimately any locking technique is going to hit the same throughput because that limit is enforced on Google's side.

**Comment by pawciobiel** [comment]
According to https://developers.google.com/sheets/api/limits

> Users can submit multiple requests at the same time, as long as they're within the quota limit.
and also:
> All Sheets requests are applied atomically.

so locking seams like an incorrect approach here - there is no point in asyncio if you serialize all IO calls.

**Comment by dgilman** [comment]
It is totally valid to blast all the requests in at once. However, the rate limits for these APIs are very aggressive. In the project that this library was written for we were hitting the API limits right away pretty much every time.

The Google APIs also return a surprising amount of 503s over time. Those all need backoff and to be retried. So with rate limits + retries, you're looking at a program that expects to spend a decent chunk of time blocked and waiting to make the next request. This is a case where asyncio shines - you can have a lot of parallel requests (and coroutines) outstanding, all waiting for their opportunity to go, and you can let the async runtime take care of all of them. The program this library was written for has been chugging along, serving lots of parallel coroutines since 2018 or so when I wrote it.

**Comment by pawciobiel** [comment]
> This is a case where asyncio shines

:-D except that you don't use asyncio, you use lock to serialize all HTTP requests and run them in the executor thread.
I'm not against using thread for a blocking calls, but let's be honest, this is not asyncio.
